// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.demo.sdk;

public interface BilateralStreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.BilateralStreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverMessage = 1;</code>
   * @return The serverMessage.
   */
  java.lang.String getServerMessage();
  /**
   * <code>string serverMessage = 1;</code>
   * @return The bytes for serverMessage.
   */
  com.google.protobuf.ByteString
      getServerMessageBytes();
}
