// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.demo.sdk;

public interface BilateralStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.BilateralStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientMessage = 1;</code>
   * @return The clientMessage.
   */
  java.lang.String getClientMessage();
  /**
   * <code>string clientMessage = 1;</code>
   * @return The bytes for clientMessage.
   */
  com.google.protobuf.ByteString
      getClientMessageBytes();
}
