// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.demo.sdk;

public interface FindDemoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.FindDemoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bytes image = 2;</code>
   * @return The image.
   */
  com.google.protobuf.ByteString getImage();
}
