// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.demo.sdk;

public interface InsertDemoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.InsertDemoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool message = 1;</code>
   * @return The message.
   */
  boolean getMessage();
}
