// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UploadFile.proto

package com.demo.sdk;

public interface UploadDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.UploadDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * base64
   * </pre>
   *
   * <code>bytes image = 1;</code>
   * @return The image.
   */
  com.google.protobuf.ByteString getImage();
}
