// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UploadFile.proto

package com.demo.sdk;

public final class UploadFileProto {
  private UploadFileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_UploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_UploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_UploadDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_UploadDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_UploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_UploadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020UploadFile.proto\022\004demo\"6\n\rUploadReques" +
      "t\022%\n\004data\030\001 \003(\0132\027.demo.UploadDataRequest" +
      "\"\"\n\021UploadDataRequest\022\r\n\005image\030\001 \001(\014\"!\n\016" +
      "UploadResponse\022\017\n\007success\030\001 \001(\0102\205\001\n\nUplo" +
      "adFile\0227\n\006upload\022\023.demo.UploadRequest\032\024." +
      "demo.UploadResponse\"\000(\001\022>\n\017uploadNotStre" +
      "am\022\023.demo.UploadRequest\032\024.demo.UploadRes" +
      "ponse\"\000B\'\n\014com.demo.sdkB\017UploadFileProto" +
      "P\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_UploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_UploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_UploadRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_demo_UploadDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_UploadDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_UploadDataRequest_descriptor,
        new java.lang.String[] { "Image", });
    internal_static_demo_UploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_demo_UploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_UploadResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
