// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package org.bytedeco.javacppexample.jni;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@NoOffset @Properties(inherit = org.bytedeco.javacppexample.presets.algo_service.class)
public class AlgoService extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public AlgoService(Pointer p) { super(p); }

  public AlgoService(@StdString BytePointer streamUrl) { super((Pointer)null); allocate(streamUrl); }
  private native void allocate(@StdString BytePointer streamUrl);
  public AlgoService(@StdString String streamUrl) { super((Pointer)null); allocate(streamUrl); }
  private native void allocate(@StdString String streamUrl);
  public native @Cast("bool") boolean init();
  public native void start();
  public native @SharedPtr AlgoResponse getResult(@SharedPtr AlgoRequest algo_request);
  public native @ByVal AlgoResponse getResult2(@ByRef AlgoRequest algo_request);
  // std::shared_ptr<MediaData> getFrame();
  public native @Cast("bool") boolean stop();
}
