// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.demo.sdk;

public final class DemoProto {
  private DemoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_BilateralStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_BilateralStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_BilateralStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_BilateralStreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_FindDemoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_FindDemoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_conditionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_conditionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_DemoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_DemoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_FindDemoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_FindDemoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_UpdateDemoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_UpdateDemoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_UpdateDemoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_UpdateDemoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_InsertDemoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_InsertDemoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DemoService.proto\022\004demo\"/\n\026BilateralSt" +
      "reamRequest\022\025\n\rclientMessage\030\001 \001(\t\"0\n\027Bi" +
      "lateralStreamResponse\022\025\n\rserverMessage\030\001" +
      " \001(\t\"2\n\020FindDemoResponse\022\017\n\007message\030\001 \001(" +
      "\t\022\r\n\005image\030\002 \001(\014\"\037\n\021conditionsRequest\022\n\n" +
      "\002id\030\001 \001(\t\"\224\001\n\013DemoRequest\022\n\n\002id\030\001 \001(\t\022\021\n" +
      "\tserialNum\030\002 \001(\t\022\017\n\007userNum\030\003 \001(\t\022\016\n\006sta" +
      "tus\030\004 \001(\005\022\014\n\004type\030\005 \001(\005\022\017\n\007message\030\006 \001(\t" +
      "\022\022\n\ncreateTime\030\007 \001(\t\022\022\n\nupdateTime\030\010 \001(\t" +
      "\"\"\n\017FindDemoRequest\022\017\n\007message\030\001 \001(\t\"$\n\021" +
      "UpdateDemoRequest\022\017\n\007message\030\001 \001(\t\"%\n\022Up" +
      "dateDemoResponse\022\017\n\007message\030\001 \001(\010\"%\n\022Ins" +
      "ertDemoResponse\022\017\n\007message\030\001 \001(\0102\244\002\n\013Dem" +
      "oService\022;\n\ninsertDemo\022\021.demo.DemoReques" +
      "t\032\030.demo.InsertDemoResponse\"\000\022=\n\010findDem" +
      "o\022\025.demo.FindDemoRequest\032\026.demo.FindDemo" +
      "Response\"\0000\001\022C\n\nupdateDemo\022\027.demo.Update" +
      "DemoRequest\032\030.demo.UpdateDemoResponse\"\000(" +
      "\001\022T\n\017bilateralStream\022\034.demo.BilateralStr" +
      "eamRequest\032\035.demo.BilateralStreamRespons" +
      "e\"\000(\0010\001B!\n\014com.demo.sdkB\tDemoProtoP\001\242\002\003H" +
      "LWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_BilateralStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_BilateralStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_BilateralStreamRequest_descriptor,
        new java.lang.String[] { "ClientMessage", });
    internal_static_demo_BilateralStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_BilateralStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_BilateralStreamResponse_descriptor,
        new java.lang.String[] { "ServerMessage", });
    internal_static_demo_FindDemoResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_demo_FindDemoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_FindDemoResponse_descriptor,
        new java.lang.String[] { "Message", "Image", });
    internal_static_demo_conditionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_demo_conditionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_conditionsRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_demo_DemoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_demo_DemoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_DemoRequest_descriptor,
        new java.lang.String[] { "Id", "SerialNum", "UserNum", "Status", "Type", "Message", "CreateTime", "UpdateTime", });
    internal_static_demo_FindDemoRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_demo_FindDemoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_FindDemoRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_demo_UpdateDemoRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_demo_UpdateDemoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_UpdateDemoRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_demo_UpdateDemoResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_demo_UpdateDemoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_UpdateDemoResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_demo_InsertDemoResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_demo_InsertDemoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_InsertDemoResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
