// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package org.bytedeco.javacppexample.global;

import org.bytedeco.javacpp.Loader;

public class algo_service_global extends org.bytedeco.javacppexample.presets.algo_service {
    static { Loader.load(); }

// Targeting ../jni/MediaDataVector.java


// Parsed from algo_service.h

// #ifndef __ALGO_SERVICE_H
// #define __ALGO_SERVICE_H

// #include <unistd.h>
// #include <string.h>
// #include <iostream>
// #include <memory>
// #include <malloc.h>
// #include <thread>
// #include <pthread.h>
// #include <time.h>
// #include <queue>

// #include <string>
// #include <vector>
// #include <algorithm>
// #include <numeric>

// #include "media_data.h"
// #include "opencv_decode.h"
// #include "algo_response.h"
// #include "algo_request.h"
// Targeting ../jni/AlgoService.java





// #endif

// Parsed from algo_request.h

//
// Created by sheng on 2022/3/12.
//

// #ifndef __ALGO_REQUEST__H
// #define __ALGO_REQUEST__H

// #include <unistd.h>
// #include <string.h>
// #include <iostream>
// #include <memory>
// #include <malloc.h>
// #include <thread>
// #include <pthread.h>
// #include <time.h>

// #include <vector>
// #include <algorithm>
// #include <numeric>
// #include <opencv2/core/utility.hpp>
// #include <opencv2/core.hpp>
// #include <opencv2/core/opengl.hpp>
// #include <opencv2/cudacodec.hpp>
// #include <opencv2/highgui.hpp>
// #include "media_data.h"
// Targeting ../jni/AlgoRequest.java



// #endif //__IMAGE_BUFFER_PLUS__H


// Parsed from algo_response.h

//
// Created by sheng on 2022/3/12.
//

// #ifndef __ALGO_RESPONSE__H
// #define __ALGO_RESPONSE__H

// #include <unistd.h>
// #include <string.h>
// #include <iostream>
// #include <memory>
// #include "media_data.h"
// Targeting ../jni/AlgoResponse.java



// #endif //__IMAGE_BUFFER_PLUS__H


}
