// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package org.bytedeco.javacppexample.global;

import org.bytedeco.javacpp.*;



public class common_global extends org.bytedeco.javacppexample.presets.common {
    static { Loader.load(); }

// Parsed from media_data.h

//
// Created by sheng on 2022/3/12.
//

// #ifndef __MEDIA_DATA__H
// #define __MEDIA_DATA__H

// #include <unistd.h>
// #include <string.h>
// #include <memory>
// #include <malloc.h>
// #include <thread>
// #include <pthread.h>
// #include <time.h>
// #include <vector>
/** enum MediaType */
public static final int
    IMAGE_JPEG = 0, VIDEO_MP4 = 1;
// Targeting ../jni/MediaData.java



// #endif //__IMAGE_BUFFER_PLUS__H


}
