// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package org.bytedeco.javacppexample.global;

import org.bytedeco.javacpp.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

public class javacpp_example_global extends org.bytedeco.javacppexample.presets.javacpp_example {
    static { Loader.load(); }

// Targeting ../jni/MediaDataVector.java


// Targeting ../jni/ByteVectorVector.java


// Targeting ../jni/StringVector.java


// Parsed from javacpp_example.h

//
// Created by sheng on 2022/3/12.
//

// #ifndef JAVACPP_EXAMPLE_H
// #define JAVACPP_EXAMPLE_H
// #include <unistd.h>
// #include <string.h>
// #include <iostream>
// #include <memory>
// #include <malloc.h>
// #include <thread>
// #include <pthread.h>
// #include <time.h>
// #include <fstream>
// #include <vector>
// #include "media_data.h"
// #include "javacpp_demo.h"
// Targeting ../jni/JavaCppExample.java



// #endif //JAVACPP_EXAMPLE_H


}
