// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JavacppDemoService.proto

package com.demo.sdk;

public final class DemoProto {
  private DemoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_FindDemoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_FindDemoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_FindDemoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_FindDemoRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030JavacppDemoService.proto\022\004demo\"2\n\020Find" +
      "DemoResponse\022\017\n\007message\030\001 \001(\t\022\r\n\005image\030\002" +
      " \001(\014\"\"\n\017FindDemoRequest\022\017\n\007message\030\001 \001(\t" +
      "2S\n\022JavacppDemoService\022=\n\010findDemo\022\025.dem" +
      "o.FindDemoRequest\032\026.demo.FindDemoRespons" +
      "e\"\0000\001B!\n\014com.demo.sdkB\tDemoProtoP\001\242\002\003HLW" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_FindDemoResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_FindDemoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_FindDemoResponse_descriptor,
        new java.lang.String[] { "Message", "Image", });
    internal_static_demo_FindDemoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_FindDemoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_FindDemoRequest_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
