// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JavacppDemoService.proto

package com.demo.sdk;

public interface FindDemoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.FindDemoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
