
server:
  port: 8080

# 日志配置
logging:
  level:
    # 注意注意注意 一定要修改成自己的包名
    # 如果你只需要输出info，可以不用修改成自己的包名，但是如果为其他级别，
    # 比如debug必修改成自己的包名才会生效
    com.concise.demo: debug
  file:
    path: /mnt/logs/springboot-demo-lock

spring:
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 192.168.190.28
    # Redis服务器连接端口
    port: 36379
    # Redis服务器连接密码（默认为空）
    password: QWER@1234
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
